version: "3.9"

services:
  postgres:
    container_name: postgresql
    # hostname: my-postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextfinsight
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - next-finsight-network
  nextjs-app:
    container_name: docker-next-finsight
    image: docker-next-finsight-image
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    volumes:
      - postgres-data:/app/postgres-data
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://username:password@postgresql:5432/nextfinsight?schema=public&connect_timeout=60
    networks:
      - next-finsight-network
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  next-finsight-network:
    driver: bridge
