import { ThemeProvider } from "@emotion/react";
import Navbar from "./(shared)/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
// import { useMemo } from "react";
// import { createTheme } from "@mui/material/styles";
// import { themeSettings } from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const theme = useMemo(() => createTheme(themeSettings), []);
  return (
    // <ThemeProvider theme={theme}>
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar />
        {children}
      </body>
    </html>
    // </ThemeProvider>
  );
}
